export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const DELETE_PRODUCT_IN_CART = 'DELETE_PRODUCT_IN_CART';
export const INCREASE_PRODUCT_IN_CART= 'INCREASE_PRODUCT_IN_CART';
export const DELETE_FOREVER_PRODUCT_IN_CART ='DELETE_FOREVER_PRODUCT_IN_CART';